spring:
  application:
    name: department
        
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

microservices:
  employee:
    url: http://${EUREKA_SERVER}:8080 

    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}:8080/eureka/  
  instance:
    preferIpAddress: true     